<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-06-17T21:52:04 EDT" name="Default suite" finished-at="2021-06-17T21:52:14 EDT" duration-ms="9260">
    <groups>
    </groups>
    <test started-at="2021-06-17T21:52:04 EDT" name="Default test" finished-at="2021-06-17T21:52:14 EDT" duration-ms="9260">
      <class name="com.salesforce.testscripts.LoginPageTest">
        <test-method is-config="true" signature="start()[pri:0, instance:com.salesforce.testscripts.LoginPageTest@2abf4075]" started-at="2021-06-17T21:52:04 EDT" name="start" finished-at="2021-06-17T21:52:07 EDT" duration-ms="2194" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method signature="invalidCredentials()[pri:0, instance:com.salesforce.testscripts.LoginPageTest@2abf4075]" started-at="2021-06-17T21:52:07 EDT" name="invalidCredentials" finished-at="2021-06-17T21:52:08 EDT" duration-ms="1120" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Please ch your username and password. If you still can't log in, contact your Salesforce administrator.] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Please ch your username and password. If you still can't log in, contact your Salesforce administrator.] but found []
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.salesforce.testscripts.LoginPageTest.invalidCredentials(LoginPageTest.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidCredentials -->
        <test-method is-config="true" signature="stop()[pri:0, instance:com.salesforce.testscripts.LoginPageTest@2abf4075]" started-at="2021-06-17T21:52:08 EDT" name="stop" finished-at="2021-06-17T21:52:09 EDT" duration-ms="1152" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stop -->
        <test-method is-config="true" signature="start()[pri:0, instance:com.salesforce.testscripts.LoginPageTest@2abf4075]" started-at="2021-06-17T21:52:09 EDT" name="start" finished-at="2021-06-17T21:52:11 EDT" duration-ms="1648" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method signature="validCredentials()[pri:0, instance:com.salesforce.testscripts.LoginPageTest@2abf4075]" started-at="2021-06-17T21:52:11 EDT" name="validCredentials" finished-at="2021-06-17T21:52:13 EDT" duration-ms="2418" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentials -->
        <test-method is-config="true" signature="stop()[pri:0, instance:com.salesforce.testscripts.LoginPageTest@2abf4075]" started-at="2021-06-17T21:52:13 EDT" name="stop" finished-at="2021-06-17T21:52:14 EDT" duration-ms="690" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stop -->
      </class> <!-- com.salesforce.testscripts.LoginPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
